config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root to:'home#index'
  resources :medical_examination
  resources :users
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  require 'csv'
end

app/models/doctor.rb
class Doctor < ApplicationRecord
end

app/models/hospital.rb
class Hospital < ApplicationRecord
end

app/models/import_csv.rb
class ImportCsv < ApplicationRecord

    def self.hospital_data(path)
        list = []
        CSV.foreach(path, headers: true) do |row|
            list << {
                name: row["name"],
                address: row["address"],
                phone: row["phone"]
            }
        end
        puts "インポート開始"
        Hospital.create!(list)
        puts "インポートに成功しました"
    rescue ActiveModel::UnknownAttributeError => invalid
    end
end

app/models/mdeical.rb
class Mdeical < ApplicationRecord
    belongs_to :users_medicines
end

app/models/medical_examination.rb
class MedicalExamination < ApplicationRecord
  belongs_to :user
end

app/models/medicine.rb
class Medicine < ApplicationRecord
  belongs_to :users
  has_many :user_medicines
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :medical_examinations, dependent: :destroy

  has_many :medicines
  has_many :user_medicines
end

app/models/user_medicine.rb
class UserMedicine < ApplicationRecord
  belongs_to :user
  belongs_to :medicine
end

app/models/users_medicine.rb
class UsersMedicine < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname]) # 新規登録時(sign_up時)にnameというキーのパラメーターを追加で許可する
  end
end

app/controllers/concerns/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def edit
    @user = User.find(params[:id])
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
   def index
    @user = User.new
  end

  def new
    @user= User.new
  end

  def edit
  end

  def create
    @user.create(user_params)
    redeirect_to action: :index
  end

  def show
  end

  def update
  end

  def destory
  end
end

app/controllers/medical_examination_controller.rb
class MedicalExaminationController < ApplicationController

  def index
    @user = User.find_by(id:current_user.id)
    gon.labels = ["1月","2月","3月","4月","5月","6月"]
    gon.data  =  MedicalExamination.where(user_id: @user).pluck(:weight).to_a
    @medical_examinations = MedicalExamination.all
  end

  def new
    @user = User.find_by(id:current_user.id)
    gon.labels = ["1月","2月","3月","4月","5月","6月"]
    gon.data = MedicalExamination.where(user_id: @user).pluck(:weight).to_a
    @medical_examination= MedicalExamination.new
  end

  def create
    @medical_examination = MedicalExamination.new(medical_params)
    if @medical_examination.save
      redirect_to action: :index
    end
  end

  def edit
  end

  def show
  end
  
  def update
  end
  
  def destroy
  end

  def medical_params
    params.require(:medical_examination).permit(:weight,:body_temp,:systolic_bp,:diastorlic_bp).merge(user_id: current_user.id)
  end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = MedicalExamination.new
  end

  def create
   MedicalExamination.create(user_params)
 end

 private
  def user_params
    params.require(:user).permit(:user_id, :weight, :body_temp, :systolic_bp, :diastorlic_bp, :memo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DocterChatApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= Gon::Base.render_data %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <%= link_to "Doctor-chat", "/", class: "navbar-brand mr-auto" %>
      <% if user_signed_in? %>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item" >
          <%= link_to "問診票",new_medical_examination_path, class: "nav-link" %>
        </li>
        <li class="nav-item" >
          <%= link_to "お薬手帳","#", class: "nav-link" %>
        </li>
        <li class="nav-item" >
          <%= link_to "担当医とチャット","#", class: "nav-link" %>
        </li>
        <li class="nav-item" >
          <%= link_to "医者の評判","#", class: "nav-link" %>
        </li>
        <li class="nav-item" >
          <%= link_to "病院の評判","#", class: "nav-link" %>
        </li>
        <li class="nav-item" >
          <%= link_to "医学書籍検索","#", class: "nav-link" %>
        </li>
        <li class="nav-item" >
          <%= link_to "ログアウト",destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item active">
          <%= link_to "新規登録", new_user_registration_path, method: :get, class: "navbar-brand" %>
        </li>
        <li class="nav-item active">
        　<%= link_to "ログイン", new_user_session_path, method: :get, class: "navbar-brand" %>
        </li>


      </ul>
      <% end %>
  </nav>
    <% if flash[:notice]%>
      <div class="alert alert-info">
        <%= flash[:notice]%>
      </div>
    <% end %>
    <% if flash.now[:alert] %>
      <div class="alert alert-danger">
        <%= flash.now[:alert]%>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>